### PR TITLE
Fix casting

### LINKED ISSUE #36: BUG: converting to double results to 0
**Description**
When casting the BigDecimal variable to double the value is getting zero

**Error/Exception Message**
No

**Expected Behavior**
The value should be correctly converted to double

**Actual Behavior**
The value is getting zero

**Steps To Reproduce**
```
 Thread.CurrentThread.CurrentCulture = new CultureInfo("en-US");

 var temp = BigDecimal.Pow(10, -1);
 var value = new BigDecimal(99.00000001);
 var res = BigDecimal.Divide(value, temp);

 double res2 = (double)res;
```

### PR DESCRIPTION
**Pull request by Bykiev**
This PR fixes casting `BigDecimal` to `double`, `Single` and `decimal` types

Closes #36

### CODE REVIEW

**Comment by Bykiev** [comment]
@Protiguous, can you please review this PR too?

**Comment by Protiguous** [comment]
All 1170 tests of 1170 tests pass!

**Comment by Bykiev** [comment]
@Protiguous, this PR reverted the previous commit, can you please fix it?

**Comment by Protiguous** [comment]
Interesting.

I'll see what I can do.

**Comment by Protiguous** [comment]
The last commit [98c6051](https://github.com/AdamWhiteHat/BigDecimal/pull/41/commits/98c6051bd99fc73ce6daf65710bd5a509f847dc1) in your pull request had the "@Bykiev
[Revert "Fix using comma as decimal separator"](https://github.com/AdamWhiteHat/BigDecimal/pull/41/commits/98c6051bd99fc73ce6daf65710bd5a509f847dc1)" in it.

**Pull request merged**
