### PR TITLE
Reapply "Fix using comma as decimal separator"

### PR DESCRIPTION
**Pull request by Bykiev**
This reverts commit 98c6051bd99fc73ce6daf65710bd5a509f847dc1.

### CODE REVIEW

**Comment by AdamWhiteHat** [comment]
@Protiguous In the future, please allow me to be the one to merge contributions, unless I ask you to or I'm MIA for a month or something. 
I would like to be the gatekeeper of this project.
For the last several contributions I have not gotten to scrutinize the code before it got merged in.
So to ensure I get a chance to review the pull requests, please allow me to be the one to merge them into the main branch.

**Comment by Bykiev** [comment]
@AdamWhiteHat, right now only https://github.com/AdamWhiteHat/BigDecimal/issues/36 was merged.
When I've created the new branch i did a mistake and created the branch based on my previous changes, that's why I thought I should revert these changes in the new branch, but it seems I shouldn't. So, I ve reapplied the reverted commit in this PR

**Comment by AdamWhiteHat** [comment]
Yes, I see that. I will approve your revert of your revert.

 I was just trying to communicate with Protiguous, but I see he has an email on his profile page, so Ill just email him instead.


Question: What version of visual studio are you running, and why does it seemingly not respect the .editorconfig? 

For example, in the file /TestBigDecimal/TestBigDecimalCritical.cs
For all the methods, the curly braces are not on a new line:
`public void TestConstructor1() {`

The presence of the the .editorconfig in the project's root directory is supposed to enforce the curly braces to be on a new line:
```
public void TestConstructor1() 
{
```

Do you have this option checked in the visual studio options? Please ensure that you do.
image

Its not a huge deal, its just annoying is all. It results in a lot of single line changes that show up in the diff that are not important, but must be sifted through when reviewing the code.

**Comment by AdamWhiteHat** [comment]
Never mind, your not responsible for inconsistent code style between the library code files and the tests, Protiguous is. 

And as far as I can tell, your IDE _was_ following the .editorconfig files... the ones Protiguous checked in...

Sorry to accuse you like that.

**Comment by Bykiev** [comment]
No problem, thank you for this library. When it will be available on github?
About formatting - I've already asked about it in discussion https://github.com/AdamWhiteHat/BigDecimal/discussions/38

**Comment by Protiguous** [comment]
I am totally fine with you gatekeeping the merges into main. :)

I was not aware of any code style changes that were not respecting `.editorconfig`?
My Visual Studio has the “Follow project coding conventions” clicked on.

**Pull request merged**
